Numpy

In [1]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\ASUS\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

#create 1D array using numpy
arr1= np.array([1,2,3,4,5]) 
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
#reshaping 1D array to 2D array
arr2=np.array([1,2,3,4,5,6])
arr2.reshape(1,6)
print(arr2)
print(arr2.shape)
# print(arr2)

[1 2 3 4 5 6]
(6,)


In [11]:
arr3= np.arange(0,20,2)
print(arr3)
print(arr3.reshape(2,5))

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]


InBuilt Functions

In [14]:
np.ones((3,4)) # array of element 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.eye(4) #identity matrix 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Numpy Vectorized Operation

In [24]:
arr4= np.array([1,2,3,4,5])
arr5= np.array([10,20,30,40,50])

#addition
print("addition", arr4+arr5)

#substraction
print("substraction", arr5-arr4)

#multiplication
print("multiplication", arr4*arr5)

#division
print("divison",arr5/arr4)



addition [11 22 33 44 55]
substraction [ 9 18 27 36 45]
multiplication [ 10  40  90 160 250]
divison [10. 10. 10. 10. 10.]


Universal Function

In [ ]:
print("Square Root ", np.sqrt(arr5))
print("exponential", np.exp(arr5))
print("sin Operation", np.sin(arr5))

Square Root  [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
exponential [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
sin  [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]


Slicing Operation & Indexing



In [31]:
arr6=np.array([[1,2,4],[5,6,7],[8,9,0]])
print(arr6)

[[1 2 4]
 [5 6 7]
 [8 9 0]]


In [ ]:
print(arr6[0][0])
print(arr6[0:,2:])

1
[[4]
 [7]
 [0]]


In [37]:
#modify
arr6[0,0]=10
print(arr6)

[[10  2  4]
 [ 5  6  7]
 [ 8  9  0]]


Statistical Concept--->Normalisation

In [39]:
#to have a mean of 0 and standard deviation of 1
data= np.array([1,2,3,4,5])

mean= np.mean(data)
std_dev= np.std(data)

normalisation= (data-mean)/std_dev
print("Normalization is ", normalisation)

Normalization is  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [46]:
#logical operation

data2=np.array([1,2,3,4,5,6,7,8,9,10])
print(data2>5)
print(data2[data2>5])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
